# File: k8s/backend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-backend
spec:
  replicas: 1  # Set to 1 for testing
  selector:
    matchLabels:
      app: chat-backend
  template:
    metadata:
      labels:
        app: chat-backend
    spec:
      containers:
        - name: chat-backend
          image: jonathanleahy/chat-backend:latest
          ports:
            - containerPort: 3000
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@rabbitmq-service:5672/"
            - name: DEBUG
              value: "true"  # Enable debug logging
---
apiVersion: v1
kind: Service
metadata:
  name: chat-backend-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30090
      protocol: TCP
  selector:
    app: chat-backend