FROM golang:1.23.2-alpine

WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy source code
COPY . .

# Build the application
RUN go build -o main .

EXPOSE 3000

# Run the application
CMD ["./main"]